<?xml version="1.0" encoding="utf-8"?><Database Name="OSM_Data_DB" Class="OSMDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=NIKITA-LENOVO;Initial Catalog=OSM_Data_DB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="OSM_Data_DBConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Nodes" Member="Nodes">
    <Type Name="Node">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="Latitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Longitude" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Association Name="Node_NodeTag" Member="NodeTags" ThisKey="NodeID" OtherKey="NodeID" Type="NodeTag" />
      <Association Name="Node_WayNode" Member="WayNodes" ThisKey="NodeID" OtherKey="NodeID" Type="WayNode" />
    </Type>
  </Table>
  <Table Name="dbo.NodeTags" Member="NodeTags">
    <Type Name="NodeTag">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="NodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TagValue" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Node_NodeTag" Member="Node" ThisKey="NodeID" OtherKey="NodeID" Type="Node" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.WayNodes" Member="WayNodes">
    <Type Name="WayNode">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WayID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="NodeID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Node_WayNode" Member="Node" ThisKey="NodeID" OtherKey="NodeID" Type="Node" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
      <Association Name="Way_WayNode" Member="Way" ThisKey="WayID" OtherKey="WayID" Type="Way" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.Ways" Member="Ways">
    <Type Name="Way">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WayID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Association Name="Way_WayNode" Member="WayNodes" ThisKey="WayID" OtherKey="WayID" Type="WayNode" />
      <Association Name="Way_WayTag" Member="WayTags" ThisKey="WayID" OtherKey="WayID" Type="WayTag" />
    </Type>
  </Table>
  <Table Name="dbo.WayTags" Member="WayTags">
    <Type Name="WayTag">
      <Column Name="ID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="WayID" Type="System.Int64" DbType="BigInt NOT NULL" CanBeNull="false" />
      <Column Name="TagName" Type="System.String" DbType="NVarChar(40) NOT NULL" CanBeNull="false" />
      <Column Name="TagValue" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Association Name="Way_WayTag" Member="Way" ThisKey="WayID" OtherKey="WayID" Type="Way" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
</Database>