#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.19448
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Diploma.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="OSM_Data_DB")]
	public partial class OSMDataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Определения метода расширяемости
    partial void OnCreated();
    partial void InsertNode(Node instance);
    partial void UpdateNode(Node instance);
    partial void DeleteNode(Node instance);
    partial void InsertNodeTag(NodeTag instance);
    partial void UpdateNodeTag(NodeTag instance);
    partial void DeleteNodeTag(NodeTag instance);
    partial void InsertWayNode(WayNode instance);
    partial void UpdateWayNode(WayNode instance);
    partial void DeleteWayNode(WayNode instance);
    partial void InsertWay(Way instance);
    partial void UpdateWay(Way instance);
    partial void DeleteWay(Way instance);
    partial void InsertWayTag(WayTag instance);
    partial void UpdateWayTag(WayTag instance);
    partial void DeleteWayTag(WayTag instance);
    #endregion
		
		public OSMDataClassesDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["OSM_Data_DBConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public OSMDataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OSMDataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OSMDataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public OSMDataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Node> Nodes
		{
			get
			{
				return this.GetTable<Node>();
			}
		}
		
		public System.Data.Linq.Table<NodeTag> NodeTags
		{
			get
			{
				return this.GetTable<NodeTag>();
			}
		}
		
		public System.Data.Linq.Table<WayNode> WayNodes
		{
			get
			{
				return this.GetTable<WayNode>();
			}
		}
		
		public System.Data.Linq.Table<Way> Ways
		{
			get
			{
				return this.GetTable<Way>();
			}
		}
		
		public System.Data.Linq.Table<WayTag> WayTags
		{
			get
			{
				return this.GetTable<WayTag>();
			}
		}
		
		public System.Data.Linq.Table<AllGraphNode> AllGraphNodes
		{
			get
			{
				return this.GetTable<AllGraphNode>();
			}
		}
		
		public System.Data.Linq.Table<ChertanovoGraphNodes> ChertanovoGraphNodes
		{
			get
			{
				return this.GetTable<ChertanovoGraphNodes>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Nodes")]
	public partial class Node : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _NodeID;
		
		private double _Latitude;
		
		private double _Longitude;
		
		private EntitySet<NodeTag> _NodeTags;
		
		private EntitySet<WayNode> _WayNodes;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNodeIDChanging(long value);
    partial void OnNodeIDChanged();
    partial void OnLatitudeChanging(double value);
    partial void OnLatitudeChanged();
    partial void OnLongitudeChanging(double value);
    partial void OnLongitudeChanged();
    #endregion
		
		public Node()
		{
			this._NodeTags = new EntitySet<NodeTag>(new Action<NodeTag>(this.attach_NodeTags), new Action<NodeTag>(this.detach_NodeTags));
			this._WayNodes = new EntitySet<WayNode>(new Action<WayNode>(this.attach_WayNodes), new Action<WayNode>(this.detach_WayNodes));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", DbType="BigInt NOT NULL")]
		public long NodeID
		{
			get
			{
				return this._NodeID;
			}
			set
			{
				if ((this._NodeID != value))
				{
					this.OnNodeIDChanging(value);
					this.SendPropertyChanging();
					this._NodeID = value;
					this.SendPropertyChanged("NodeID");
					this.OnNodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Latitude", DbType="Float NOT NULL")]
		public double Latitude
		{
			get
			{
				return this._Latitude;
			}
			set
			{
				if ((this._Latitude != value))
				{
					this.OnLatitudeChanging(value);
					this.SendPropertyChanging();
					this._Latitude = value;
					this.SendPropertyChanged("Latitude");
					this.OnLatitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Longitude", DbType="Float NOT NULL")]
		public double Longitude
		{
			get
			{
				return this._Longitude;
			}
			set
			{
				if ((this._Longitude != value))
				{
					this.OnLongitudeChanging(value);
					this.SendPropertyChanging();
					this._Longitude = value;
					this.SendPropertyChanged("Longitude");
					this.OnLongitudeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Node_NodeTag", Storage="_NodeTags", ThisKey="NodeID", OtherKey="NodeID")]
		public EntitySet<NodeTag> NodeTags
		{
			get
			{
				return this._NodeTags;
			}
			set
			{
				this._NodeTags.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Node_WayNode", Storage="_WayNodes", ThisKey="NodeID", OtherKey="NodeID")]
		public EntitySet<WayNode> WayNodes
		{
			get
			{
				return this._WayNodes;
			}
			set
			{
				this._WayNodes.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NodeTags(NodeTag entity)
		{
			this.SendPropertyChanging();
			entity.Node = this;
		}
		
		private void detach_NodeTags(NodeTag entity)
		{
			this.SendPropertyChanging();
			entity.Node = null;
		}
		
		private void attach_WayNodes(WayNode entity)
		{
			this.SendPropertyChanging();
			entity.Node = this;
		}
		
		private void detach_WayNodes(WayNode entity)
		{
			this.SendPropertyChanging();
			entity.Node = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NodeTags")]
	public partial class NodeTag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _NodeID;
		
		private string _TagName;
		
		private string _TagValue;
		
		private EntityRef<Node> _Node;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnNodeIDChanging(long value);
    partial void OnNodeIDChanged();
    partial void OnTagNameChanging(string value);
    partial void OnTagNameChanged();
    partial void OnTagValueChanging(string value);
    partial void OnTagValueChanged();
    #endregion
		
		public NodeTag()
		{
			this._Node = default(EntityRef<Node>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", DbType="BigInt NOT NULL")]
		public long NodeID
		{
			get
			{
				return this._NodeID;
			}
			set
			{
				if ((this._NodeID != value))
				{
					if (this._Node.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNodeIDChanging(value);
					this.SendPropertyChanging();
					this._NodeID = value;
					this.SendPropertyChanged("NodeID");
					this.OnNodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TagName
		{
			get
			{
				return this._TagName;
			}
			set
			{
				if ((this._TagName != value))
				{
					this.OnTagNameChanging(value);
					this.SendPropertyChanging();
					this._TagName = value;
					this.SendPropertyChanged("TagName");
					this.OnTagNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagValue", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TagValue
		{
			get
			{
				return this._TagValue;
			}
			set
			{
				if ((this._TagValue != value))
				{
					this.OnTagValueChanging(value);
					this.SendPropertyChanging();
					this._TagValue = value;
					this.SendPropertyChanged("TagValue");
					this.OnTagValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Node_NodeTag", Storage="_Node", ThisKey="NodeID", OtherKey="NodeID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Node Node
		{
			get
			{
				return this._Node.Entity;
			}
			set
			{
				Node previousValue = this._Node.Entity;
				if (((previousValue != value) 
							|| (this._Node.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Node.Entity = null;
						previousValue.NodeTags.Remove(this);
					}
					this._Node.Entity = value;
					if ((value != null))
					{
						value.NodeTags.Add(this);
						this._NodeID = value.NodeID;
					}
					else
					{
						this._NodeID = default(long);
					}
					this.SendPropertyChanged("Node");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WayNodes")]
	public partial class WayNode : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _WayID;
		
		private long _NodeID;
		
		private EntityRef<Node> _Node;
		
		private EntityRef<Way> _Way;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWayIDChanging(long value);
    partial void OnWayIDChanged();
    partial void OnNodeIDChanging(long value);
    partial void OnNodeIDChanged();
    #endregion
		
		public WayNode()
		{
			this._Node = default(EntityRef<Node>);
			this._Way = default(EntityRef<Way>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WayID", DbType="BigInt NOT NULL")]
		public long WayID
		{
			get
			{
				return this._WayID;
			}
			set
			{
				if ((this._WayID != value))
				{
					if (this._Way.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWayIDChanging(value);
					this.SendPropertyChanging();
					this._WayID = value;
					this.SendPropertyChanged("WayID");
					this.OnWayIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", DbType="BigInt NOT NULL")]
		public long NodeID
		{
			get
			{
				return this._NodeID;
			}
			set
			{
				if ((this._NodeID != value))
				{
					if (this._Node.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnNodeIDChanging(value);
					this.SendPropertyChanging();
					this._NodeID = value;
					this.SendPropertyChanged("NodeID");
					this.OnNodeIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Node_WayNode", Storage="_Node", ThisKey="NodeID", OtherKey="NodeID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Node Node
		{
			get
			{
				return this._Node.Entity;
			}
			set
			{
				Node previousValue = this._Node.Entity;
				if (((previousValue != value) 
							|| (this._Node.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Node.Entity = null;
						previousValue.WayNodes.Remove(this);
					}
					this._Node.Entity = value;
					if ((value != null))
					{
						value.WayNodes.Add(this);
						this._NodeID = value.NodeID;
					}
					else
					{
						this._NodeID = default(long);
					}
					this.SendPropertyChanged("Node");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Way_WayNode", Storage="_Way", ThisKey="WayID", OtherKey="WayID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Way Way
		{
			get
			{
				return this._Way.Entity;
			}
			set
			{
				Way previousValue = this._Way.Entity;
				if (((previousValue != value) 
							|| (this._Way.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Way.Entity = null;
						previousValue.WayNodes.Remove(this);
					}
					this._Way.Entity = value;
					if ((value != null))
					{
						value.WayNodes.Add(this);
						this._WayID = value.WayID;
					}
					else
					{
						this._WayID = default(long);
					}
					this.SendPropertyChanged("Way");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Ways")]
	public partial class Way : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _WayID;
		
		private EntitySet<WayNode> _WayNodes;
		
		private EntitySet<WayTag> _WayTags;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWayIDChanging(long value);
    partial void OnWayIDChanged();
    #endregion
		
		public Way()
		{
			this._WayNodes = new EntitySet<WayNode>(new Action<WayNode>(this.attach_WayNodes), new Action<WayNode>(this.detach_WayNodes));
			this._WayTags = new EntitySet<WayTag>(new Action<WayTag>(this.attach_WayTags), new Action<WayTag>(this.detach_WayTags));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WayID", DbType="BigInt NOT NULL")]
		public long WayID
		{
			get
			{
				return this._WayID;
			}
			set
			{
				if ((this._WayID != value))
				{
					this.OnWayIDChanging(value);
					this.SendPropertyChanging();
					this._WayID = value;
					this.SendPropertyChanged("WayID");
					this.OnWayIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Way_WayNode", Storage="_WayNodes", ThisKey="WayID", OtherKey="WayID")]
		public EntitySet<WayNode> WayNodes
		{
			get
			{
				return this._WayNodes;
			}
			set
			{
				this._WayNodes.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Way_WayTag", Storage="_WayTags", ThisKey="WayID", OtherKey="WayID")]
		public EntitySet<WayTag> WayTags
		{
			get
			{
				return this._WayTags;
			}
			set
			{
				this._WayTags.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_WayNodes(WayNode entity)
		{
			this.SendPropertyChanging();
			entity.Way = this;
		}
		
		private void detach_WayNodes(WayNode entity)
		{
			this.SendPropertyChanging();
			entity.Way = null;
		}
		
		private void attach_WayTags(WayTag entity)
		{
			this.SendPropertyChanging();
			entity.Way = this;
		}
		
		private void detach_WayTags(WayTag entity)
		{
			this.SendPropertyChanging();
			entity.Way = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.WayTags")]
	public partial class WayTag : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _ID;
		
		private long _WayID;
		
		private string _TagName;
		
		private string _TagValue;
		
		private EntityRef<Way> _Way;
		
    #region Определения метода расширяемости
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDChanging(int value);
    partial void OnIDChanged();
    partial void OnWayIDChanging(long value);
    partial void OnWayIDChanged();
    partial void OnTagNameChanging(string value);
    partial void OnTagNameChanged();
    partial void OnTagValueChanging(string value);
    partial void OnTagValueChanged();
    #endregion
		
		public WayTag()
		{
			this._Way = default(EntityRef<Way>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this.OnIDChanging(value);
					this.SendPropertyChanging();
					this._ID = value;
					this.SendPropertyChanged("ID");
					this.OnIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_WayID", DbType="BigInt NOT NULL")]
		public long WayID
		{
			get
			{
				return this._WayID;
			}
			set
			{
				if ((this._WayID != value))
				{
					if (this._Way.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnWayIDChanging(value);
					this.SendPropertyChanging();
					this._WayID = value;
					this.SendPropertyChanged("WayID");
					this.OnWayIDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagName", DbType="NVarChar(40) NOT NULL", CanBeNull=false)]
		public string TagName
		{
			get
			{
				return this._TagName;
			}
			set
			{
				if ((this._TagName != value))
				{
					this.OnTagNameChanging(value);
					this.SendPropertyChanging();
					this._TagName = value;
					this.SendPropertyChanged("TagName");
					this.OnTagNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TagValue", DbType="Text NOT NULL", CanBeNull=false, UpdateCheck=UpdateCheck.Never)]
		public string TagValue
		{
			get
			{
				return this._TagValue;
			}
			set
			{
				if ((this._TagValue != value))
				{
					this.OnTagValueChanging(value);
					this.SendPropertyChanging();
					this._TagValue = value;
					this.SendPropertyChanged("TagValue");
					this.OnTagValueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Way_WayTag", Storage="_Way", ThisKey="WayID", OtherKey="WayID", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public Way Way
		{
			get
			{
				return this._Way.Entity;
			}
			set
			{
				Way previousValue = this._Way.Entity;
				if (((previousValue != value) 
							|| (this._Way.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Way.Entity = null;
						previousValue.WayTags.Remove(this);
					}
					this._Way.Entity = value;
					if ((value != null))
					{
						value.WayTags.Add(this);
						this._WayID = value.WayID;
					}
					else
					{
						this._WayID = default(long);
					}
					this.SendPropertyChanged("Way");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.AllGraphNodes")]
	public partial class AllGraphNode
	{
		
		private long _Way1;
		
		private long _Way2;
		
		private long _NodeID;
		
		private System.Nullable<long> _RowNum;
		
		public AllGraphNode()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Way1", DbType="BigInt NOT NULL")]
		public long Way1
		{
			get
			{
				return this._Way1;
			}
			set
			{
				if ((this._Way1 != value))
				{
					this._Way1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Way2", DbType="BigInt NOT NULL")]
		public long Way2
		{
			get
			{
				return this._Way2;
			}
			set
			{
				if ((this._Way2 != value))
				{
					this._Way2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", DbType="BigInt NOT NULL")]
		public long NodeID
		{
			get
			{
				return this._NodeID;
			}
			set
			{
				if ((this._NodeID != value))
				{
					this._NodeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChertanovoGraphNodes")]
	public partial class ChertanovoGraphNodes
	{
		
		private long _Way1;
		
		private long _Way2;
		
		private long _NodeID;
		
		private System.Nullable<long> _RowNum;
		
		public ChertanovoGraphNodes()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Way1", DbType="BigInt NOT NULL")]
		public long Way1
		{
			get
			{
				return this._Way1;
			}
			set
			{
				if ((this._Way1 != value))
				{
					this._Way1 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Way2", DbType="BigInt NOT NULL")]
		public long Way2
		{
			get
			{
				return this._Way2;
			}
			set
			{
				if ((this._Way2 != value))
				{
					this._Way2 = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NodeID", DbType="BigInt NOT NULL")]
		public long NodeID
		{
			get
			{
				return this._NodeID;
			}
			set
			{
				if ((this._NodeID != value))
				{
					this._NodeID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_RowNum", DbType="BigInt")]
		public System.Nullable<long> RowNum
		{
			get
			{
				return this._RowNum;
			}
			set
			{
				if ((this._RowNum != value))
				{
					this._RowNum = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
